name: Build VoodooPS2
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: VoodooInput Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/VoodooInput/master/VoodooInput/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - name: Build Release
        run: xcodebuild -project VoodooPS2Controller.xcodeproj -configuration Release -jobs 1
      - uses: actions/upload-artifact@v4
        with:
          name: VoodooPS2-kexts
          path: build/Products/Release/VoodooPS2Controller.kext
 
